### Metodo de registrar estudiante
## Ejemplo 01
POST http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Dayiro",
  "lastName":"Alvis",
  "typeDoc": "DNI",
  "numDoc": "45438154",
  "grade": "5to grado",
  "parentId": 1
}

###
## Ejemplo 02
POST http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Dafne",
  "lastName":"Alvis",
  "typeDoc": "DNI",
  "numDoc": "45438151",
  "grade": "4to grado",
  "parentId": 1
}

###
## Ejemplo 03
POST http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Yassiel",
  "lastName":"Alvis",
  "typeDoc": "DNI",
  "numDoc": "45438152",
  "grade": "2to grado",
  "parentId": 1
}