### Metodo de registrar estudiante
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDUyODIwOSwiZXhwIjoxNzY0NTM1NDA5fQ.tW1ugPtEkbLXL-L0s0iyL0YNm_1gQBQK36Ixez9EArY

## Ejemplo 01
POST http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Dafne Yassiel",
  "lastName":"Huamanttupa",
  "grade": "4to grado",
  "parentId": 1
}
