### Metodo de registrar estudiante
## Ejemplo 01
POST http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Dafne Yassiel",
  "lastName":"Huamanttupa",
  "grade": "4to grado",
  "parentId": 1
}
