### Metodo de cambiar contraseña
@token = 6f1ad32705d7ca963f49d32aefcebd4678ac0f4f7e5e8aa38fbf0be62866fc69

## Ejemplo 01
POST http://localhost:3000/auth/reset-password
Content-Type: application/json


{
  "token": "{{token}}",
  "newPassword": "123456"
}